import Foundation
import FoundationModels

/// CommandResult is the structured output generated by the Foundation Models session.
/// Using @Generable guarantees structural correctness via constrained decoding.
@Generable
struct CommandResult {
    @Guide(description: "The exact CLI command to execute. Output only the raw command with no markdown, backticks, or explanation text.")
    var command: String

    @Guide(description: "A single sentence explaining what this command does, shown to the user before execution.")
    var explanation: String
}

/// Builds the user-facing prompt from BridgeInput.
func buildPrompt(_ input: BridgeInput) -> String {
    var parts: [String] = []

    if !input.schema.isEmpty {
        parts.append("Available commands:\n\(input.schema)")
    }

    if !input.examples.isEmpty {
        var exLines = "Examples:"
        for ex in input.examples {
            if ex.count == 2 {
                exLines += "\n  User: \(ex[0])\n  Command: \(ex[1])"
            }
        }
        parts.append(exLines)
    }

    parts.append("User: \(input.intent)\nCommand:")
    return parts.joined(separator: "\n\n")
}

@main
struct NLCIApple {
    static func main() {
        Task {
            // --ping mode: check availability and exit
            if CommandLine.arguments.contains("--ping") {
                if let errStr = checkAvailability() {
                    emit(BridgeOutput(error: errStr))
                    exit(1)
                }
                emit(BridgeOutput(command: "ok", explanation: "Apple Intelligence is available"))
                exit(0)
            }

            // Read all of stdin — if EOF with no data, the Go parent has exited
            guard let inputData = try? FileHandle.standardInput.readToEnd(),
                  !inputData.isEmpty else {
                emit(BridgeOutput(error: "unavailable:stdinClosed"))
                exit(1)
            }

            // Decode BridgeInput
            let input: BridgeInput
            do {
                input = try JSONDecoder().decode(BridgeInput.self, from: inputData)
            } catch {
                emit(BridgeOutput(error: "internal:inputDecodeFailed:\(error.localizedDescription)"))
                exit(1)
            }

            // Availability gate
            if let errStr = checkAvailability() {
                emit(BridgeOutput(error: errStr))
                exit(1)
            }

            // Run inference
            do {
                let session = LanguageModelSession(instructions: input.system)

                let response = try await session.respond(
                    to: buildPrompt(input),
                    generating: CommandResult.self
                )

                emit(BridgeOutput(
                    command: response.content.command,
                    explanation: response.content.explanation
                ))
                exit(0)
            } catch {
                emit(BridgeOutput(error: "inference:\(error.localizedDescription)"))
                exit(1)
            }
        }

        // REQUIRED: drives Swift concurrency — without this, the async Task
        // never executes because the process exits before the run loop starts.
        RunLoop.main.run()
    }
}
